[programs.devnet]
backend = "4imuQ8bDKmpC1BUuEc66kCnQBa4ddVfEjuyCX69TDvrR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/florianbouron/.config/solana/id.json"

[scripts]
test = "node tests/backend.js"
